return {
  'nvim-treesitter/nvim-treesitter',
  version = false, -- last release is way too old and doesn't work on Windows
  build = ':TSUpdate',
  opts = {
    ensure_installed = {
      'bash',
      'c',
      'c_sharp',
      'cmake',
      'cpp',
      'css',
      'csv',
      'dockerfile',
      'go',
      'gdscript',
      'godot_resource',
      'gdshader',
      'html',
      'javascript',
      'json',
      'lua',
      'markdown',
      'ocaml',
      'ocaml_interface',
      'php',
      'python',
      'regex',
      'regex',
      'rust',
      'sql',
      'toml',
      'typescript',
      'vim',
      'vimdoc',
      'xml',
      'yaml',
      'zig',
    },
    autoinstall = true,
    highlight = {
      enable = true, -- false will disable the whole extension
    },
  },
}
