column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
# incorrect: require('module-name')
# correct  : require 'module-name'
no_call_parentheses = true
