#!usr/bin/env sh

# Load scritpting-addition
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Global settings
yabai -m config external_bar                 all:0:0
yabai -m config mouse_follows_focus          on
# yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.85
yabai -m config window_border                off
# yabai -m config window_border_width          6
# yabai -m config active_window_border_color   0xff775759
# yabai -m config normal_window_border_color   0xff555555
# yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# mission-control desktop labels
yabai -m space 1 --label code
yabai -m space 2 --label web
yabai -m space 3 --label notes
yabai -m space 4 --label gfx
yabai -m space 5 --label mail
yabai -m space 6 --label social
yabai -m space 7 --label media
yabai -m space 8 --label games

# specific space settings
yabai -m config --space 1 layout stack
yabai -m config --space 2 layout stack
yabai -m config --space 4 layout stack
yabai -m config --space 8 layout float

# window rules
yabai -m rule --add app="^kitty$" space=code
yabai -m rule --add app="^Alacritty$" space=code
yabai -m rule --add app="^Rider$" space=code
yabai -m rule --add app="^Brave Browser$" space=web
yabai -m rule --add app="^Safari$" space=web
yabai -m rule --add app="^Firefox$" space=web
yabai -m rule --add app="^Voorvertoning$" space=notes
yabai -m rule --add app="^Notes$" space=notes
yabai -m rule --add app="^Notities$" space=notes
yabai -m rule --add app="^Agenda$" space=notes
yabai -m rule --add app="^Blender$" space=gfx
yabai -m rule --add app="^Unity$" space=gfx
yabai -m rule --add app="^Adobe Photoshop CC 2018$" space=gfx
yabai -m rule --add app="^Adobe Indesign CC 2018$" space=gfx
yabai -m rule --add app="^Adobe Illustrator CC 2018$" space=gfx
yabai -m rule --add app="^Mail$" space=mail
yabai -m rule --add app="^Spotify$" space=media
yabai -m rule --add app="^Muziek$" space=media
yabai -m rule --add app="^Discord$" space=social
yabai -m rule --add app="^Slack$" space=social

# Apps that float:
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Systeemvoorkeuren$" manage=off
yabai -m rule --add app="^Unity Hub$" manage=off
yabai -m rule --add app="^Steam$" space=games manage=off

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
# yabai -m signal --add event=window_destroyed action="echo \"destroyed window with id \$YABAI_WINDOW_ID\""
# yabai -m signal --add event=space_changed action="echo \"changed space \$YABAI_RECENT_SPACE_ID -> \$YABAI_SPACE_ID\""
# yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# Limelight:
killall limelight &> /dev/null
limelight --config ~/.config/yabai/limelightrc.sh &> /dev/null &
