TrySource'plugins.rooter'
-- TrySource'plugins.nvim-web-devicons'
TrySource'plugins.startify'
TrySource'plugins.treesitter'
TrySource'plugins.lsp-status'
TrySource'plugins.telescope'
TrySource'plugins.lir'
-- TrySource'plugins.nvim-tree'
TrySource'Plugins.harpoon'
TrySource'plugins.git'
TrySource'plugins.gitlinker'
TrySource'plugins.git-worktree'
TrySource'plugins.zoom-vim'
