-- TrySource'plugins.rooter'
TrySource 'plugins.project'
-- TrySource'plugins.nvim-web-devicons'
-- TrySource 'plugins.startify'
-- TrySource 'plugins.dashboard'
TrySource 'plugins.alpha'
TrySource 'plugins.treesitter'
TrySource 'plugins.lsp-status'
TrySource 'plugins.telescope'
TrySource 'plugins.lir'
-- TrySource'plugins.nvim-tree'
TrySource 'plugins.luasnip'
TrySource 'Plugins.harpoon'
TrySource 'plugins.git'
TrySource 'plugins.gitlinker'
TrySource 'plugins.git-worktree'
TrySource 'plugins.stylua'
TrySource 'plugins.zoom-vim'
